- hosts: localhost
  connection: local
  become: yes
  vars:
    current_user: "{{ lookup('env','USER') }}"
  tasks:
  - name: Manage /etc/sudoers.d directory
    file:
      path: /etc/sudoers.d
      state: directory

  - name: Manage sudoers file
    community.general.sudoers:
      name: "{{ current_user }}"
      user: "{{ current_user }}"
      commands: ALL
      state: present
